DengAI: Predicting Disease Spread

In [120]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

sns.set()
pd.set_option('display.max_columns',None)

# Igore warning statements
import warnings
warnings.filterwarnings('ignore')

In [121]:
X = pd.read_csv('dengue_features_train.csv')
y = pd.read_csv('dengue_labels_train.csv')
df_test = pd.read_csv('dengue_features_test.csv')
df_test_iq = df_test[df_test['city']=='iq']
df_test_sj = df_test[df_test['city']=='sj']
holdout = df_test.copy()

df = pd.merge(X,y, left_on=['city','weekofyear','year'],right_on=['city','weekofyear','year'])
df_iq = df[df['city']=='iq']
df_sj = df[df['city']=='sj']
holdout_iq = holdout[holdout['city']=='iq']
holdout_sj = holdout[holdout['city']=='sj']

In [122]:
df.describe()

,year,weekofyear,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,reanalysis_avg_temp_k,reanalysis_dew_point_temp_k,reanalysis_max_air_temp_k,reanalysis_min_air_temp_k,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm,total_cases
count,1456.000000,1456.000000,1262.000000,1404.000000,1434.000000,1434.000000,1443.000000,1446.000000,1446.000000,1446.000000,1446.000000,1446.000000,1446.000000,1446.000000,1443.000000,1446.000000,1446.000000,1413.000000,1413.000000,1436.000000,1442.000000,1434.000000,1456.000000
mean,2001.031593,26.503434,0.142294,0.130553,0.203783,0.202305,45.760388,298.701852,299.225578,295.246356,303.427109,295.719156,40.151819,82.161959,45.760388,16.746427,4.903754,27.185783,8.059328,32.452437,22.102150,39.326360,24.675137
std,5.408314,15.019437,0.140531,0.119999,0.073860,0.083903,43.715537,1.362420,1.261715,1.527810,3.234601,2.565364,43.434399,7.153897,43.715537,1.542494,3.546445,1.292347,2.128568,1.959318,1.574066,47.455314,43.596000
min,1990.000000,1.000000,-0.406250,-0.456100,-0.015533,-0.063457,0.000000,294.635714,294.892857,289.642857,297.800000,286.900000,0.000000,57.787143,0.000000,11.715714,1.357143,21.400000,4.528571,26.700000,14.700000,0.000000,0.000000
25%,1997.000000,13.750000,0.044950,0.049217,0.155087,0.144209,9.800000,297.658929,298.257143,294.118929,301.000000,293.900000,13.055000,77.177143,9.800000,15.557143,2.328571,26.300000,6.514286,31.100000,21.100000,8.700000,5.000000
50%,2002.000000,26.500000,0.128817,0.121429,0.196050,0.189450,38.340000,298.646429,299.289286,295.640714,302.400000,296.200000,27.245000,80.301429,38.340000,17.087143,2.857143,27.414286,7.300000,32.800000,22.200000,23.850000,12.000000
75%,2005.000000,39.250000,0.248483,0.216600,0.248846,0.246982,70.235000,299.833571,300.207143,296.460000,305.500000,297.900000,52.200000,86.357857,70.235000,17.978214,7.625000,28.157143,9.566667,33.900000,23.300000,53.900000,28.000000
max,2010.000000,53.000000,0.508357,0.454429,0.538314,0.546017,390.600000,302.200000,302.928571,298.450000,314.000000,299.900000,570.500000,98.610000,390.600000,20.461429,16.028571,30.800000,15.800000,42.200000,25.600000,543.300000,461.000000

In [123]:
#missing data
total = df.isnull().sum().sort_values(ascending=False)
percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data.head(20)

                                       Total   Percent
ndvi_ne                                  194  0.133242
ndvi_nw                                   52  0.035714
station_diur_temp_rng_c                   43  0.029533
station_avg_temp_c                        43  0.029533
ndvi_se                                   22  0.015110
ndvi_sw                                   22  0.015110
station_precip_mm                         22  0.015110
station_max_temp_c                        20  0.013736
station_min_temp_c                        14  0.009615
reanalysis_sat_precip_amt_mm              13  0.008929
precipitation_amt_mm                      13  0.008929
reanalysis_max_air_temp_k                 10  0.006868
reanalysis_avg_temp_k                     10  0.006868
reanalysis_air_temp_k                     10  0.006868
reanalysis_min_air_temp_k                 10  0.006868
reanalysis_dew_point_temp_k               10  0.006868
reanalysis_precip_amt_kg_per_m2           10  0.006868
reanalysis_relative_humidity_percent      10  0.006868
reanalysis_specific_humidity_g_per_kg     10  0.006868
reanalysis_tdtr_k                         10  0.006868

In [124]:
df.info()
df_iq.drop(['week_start_date'],inplace=True,axis=1)
df_sj.drop(['week_start_date'],inplace=True,axis=1)
holdout_sj.drop(['week_start_date'],inplace=True,axis=1)
holdout_iq.drop(['week_start_date'],inplace=True,axis=1)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1456 entries, 0 to 1455
Data columns (total 25 columns):
city                                     1456 non-null object
year                                     1456 non-null int64
weekofyear                               1456 non-null int64
week_start_date                          1456 non-null object
ndvi_ne                                  1262 non-null float64
ndvi_nw                                  1404 non-null float64
ndvi_se                                  1434 non-null float64
ndvi_sw                                  1434 non-null float64
precipitation_amt_mm                     1443 non-null float64
reanalysis_air_temp_k                    1446 non-null float64
reanalysis_avg_temp_k                    1446 non-null float64
reanalysis_dew_point_temp_k              1446 non-null float64
reanalysis_max_air_temp_k                1446 non-null float64
reanalysis_min_air_temp_k                1446 non-null float64
reanalysis_precip_amt_kg_per_m2          1446 non-null float64
reanalysis_relative_humidity_percent     1446 non-null float64
reanalysis_sat_precip_amt_mm             1443 non-null float64
reanalysis_specific_humidity_g_per_kg    1446 non-null float64
reanalysis_tdtr_k                        1446 non-null float64
station_avg_temp_c                       1413 non-null float64
station_diur_temp_rng_c                  1413 non-null float64
station_max_temp_c                       1436 non-null float64
station_min_temp_c                       1442 non-null float64
station_precip_mm                        1434 non-null float64
total_cases                              1456 non-null int64
dtypes: float64(20), int64(3), object(2)
memory usage: 295.8+ KB

In [125]:
from sklearn.model_selection import train_test_split

X_train_sj,X_test_sj, y_train_sj, y_test_sj = train_test_split(df_sj.iloc[:,0:-1],df_sj['total_cases'], test_size=0.2, random_state=123)
X_train_sj.shape
X_train_iq,X_test_iq, y_train_iq, y_test_iq = train_test_split(df_iq.iloc[:,0:-1],df_iq['total_cases'], test_size=0.2, random_state=123)
X_train_iq.shape

(416, 23)

In [126]:
y_train_iq.shape

(416,)

In [127]:
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values='NaN',strategy='mean', axis=0)

imputer = imputer.fit(X_train_sj.iloc[:,2:])
X_train_sj.iloc[:,2:]= imputer.transform(X_train_sj.iloc[:,2:])
imputer = imputer.fit(X_test_sj.iloc[:,2:])
X_test_sj.iloc[:,2:]= imputer.transform(X_test_sj.iloc[:,2:])

imputer = imputer.fit(X_train_iq.iloc[:,2:])
X_train_iq.iloc[:,2:]= imputer.transform(X_train_iq.iloc[:,2:])
imputer = imputer.fit(X_test_iq.iloc[:,2:])
X_test_iq.iloc[:,2:]= imputer.transform(X_test_iq.iloc[:,2:])


imputer = imputer.fit(holdout_sj.iloc[:,2:])
holdout_sj.iloc[:,2:]= imputer.transform(holdout_sj.iloc[:,2:])
imputer = imputer.fit(holdout_sj.iloc[:,2:])
holdout_iq.iloc[:,2:]= imputer.transform(holdout_iq.iloc[:,2:])

In [128]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

le.fit(X_train_sj['city'])

X_train_sj['city']  = le.transform(X_train_sj['city'])
le.fit(X_test_sj['city'])
X_test_sj['city'] =le.transform(X_test_sj['city'])
le.fit(holdout_sj['city'])
holdout_sj['city'] =le.transform(holdout_sj['city'])


le.fit(X_train_iq['city'])

X_train_iq['city']  = le.transform(X_train_iq['city'])
le.fit(X_test_iq['city'])
X_test_iq['city'] =le.transform(X_test_iq['city'])
le.fit(holdout_iq['city'])
holdout_iq['city'] =le.transform(holdout_iq['city'])

In [129]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train_sj,y_train_sj)
y_pred_sj = lr.predict(X_test_sj)
y_holdout_sj = lr.predict(holdout_sj)

lr.fit(X_train_iq,y_train_iq)
y_pred_iq = lr.predict(X_test_iq)
y_holdout_iq = lr.predict(holdout_iq)

In [130]:
from sklearn.metrics import mean_absolute_error

mean_absolute_error(y_test_sj,y_pred_sj),mean_absolute_error(y_test_iq,y_pred_iq)

(28.930851063829788, 7.6057692307692308)

In [159]:
from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(n_estimators=300)
random_forest.fit(X_train_sj, y_train_sj)
y_pred_sj = random_forest.predict(X_test_sj)
mean_absolute_error(y_test_sj,y_pred_sj)
y_holdout_sj = random_forest.predict(holdout_sj)

random_forest.fit(X_train_iq, y_train_iq)
y_pred_iq = random_forest.predict(X_test_iq)
mean_absolute_error(y_test_iq,y_pred_iq)
y_holdout_iq = random_forest.predict(holdout_iq)

df_test_sj.reset_index(drop=True, inplace=True)
df_test_iq.reset_index(drop=True, inplace=True)

y_sj = pd.concat([df_test_sj.iloc[:,0:3],pd.DataFrame(y_holdout_sj, columns=['total_cases'])], axis=1)
y_iq = pd.concat([df_test_iq.iloc[:,0:3],pd.DataFrame(y_holdout_iq, columns=['total_cases'])], ignore_index=True, axis=1)

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"

In [154]:
final_y

    city    year  weekofyear  total_cases    0       1     2     3
0     sj  2008.0        18.0          3.0  NaN     NaN   NaN   NaN
1     sj  2008.0        19.0          7.0  NaN     NaN   NaN   NaN
2     sj  2008.0        20.0          5.0  NaN     NaN   NaN   NaN
3     sj  2008.0        21.0          5.0  NaN     NaN   NaN   NaN
4     sj  2008.0        22.0          7.0  NaN     NaN   NaN   NaN
5     sj  2008.0        23.0         10.0  NaN     NaN   NaN   NaN
6     sj  2008.0        24.0         21.0  NaN     NaN   NaN   NaN
7     sj  2008.0        25.0         21.0  NaN     NaN   NaN   NaN
8     sj  2008.0        26.0         13.0  NaN     NaN   NaN   NaN
9     sj  2008.0        27.0         10.0  NaN     NaN   NaN   NaN
10    sj  2008.0        28.0          6.0  NaN     NaN   NaN   NaN
11    sj  2008.0        29.0         10.0  NaN     NaN   NaN   NaN
12    sj  2008.0        30.0          4.0  NaN     NaN   NaN   NaN
13    sj  2008.0        31.0         13.0  NaN     NaN   NaN   NaN
14    sj  2008.0        32.0         18.0  NaN     NaN   NaN   NaN
15    sj  2008.0        33.0          4.0  NaN     NaN   NaN   NaN
16    sj  2008.0        34.0         27.0  NaN     NaN   NaN   NaN
17    sj  2008.0        35.0         16.0  NaN     NaN   NaN   NaN
18    sj  2008.0        36.0         82.0  NaN     NaN   NaN   NaN
19    sj  2008.0        37.0         55.0  NaN     NaN   NaN   NaN
20    sj  2008.0        38.0         18.0  NaN     NaN   NaN   NaN
21    sj  2008.0        39.0         55.0  NaN     NaN   NaN   NaN
22    sj  2008.0        40.0         37.0  NaN     NaN   NaN   NaN
23    sj  2008.0        41.0         20.0  NaN     NaN   NaN   NaN
24    sj  2008.0        42.0         39.0  NaN     NaN   NaN   NaN
25    sj  2008.0        43.0         48.0  NaN     NaN   NaN   NaN
26    sj  2008.0        44.0         10.0  NaN     NaN   NaN   NaN
27    sj  2008.0        45.0         10.0  NaN     NaN   NaN   NaN
28    sj  2008.0        46.0          6.0  NaN     NaN   NaN   NaN
29    sj  2008.0        47.0         33.0  NaN     NaN   NaN   NaN
..   ...     ...         ...          ...  ...     ...   ...   ...
386  NaN     NaN         NaN          NaN   iq  2012.0  48.0   8.0
387  NaN     NaN         NaN          NaN   iq  2012.0  49.0   5.0
388  NaN     NaN         NaN          NaN   iq  2012.0  50.0   4.0
389  NaN     NaN         NaN          NaN   iq  2012.0  51.0   9.0
390  NaN     NaN         NaN          NaN   iq  2013.0   1.0  10.0
391  NaN     NaN         NaN          NaN   iq  2013.0   2.0   1.0
392  NaN     NaN         NaN          NaN   iq  2013.0   3.0   2.0
393  NaN     NaN         NaN          NaN   iq  2013.0   4.0   9.0
394  NaN     NaN         NaN          NaN   iq  2013.0   5.0   4.0
395  NaN     NaN         NaN          NaN   iq  2013.0   6.0   2.0
396  NaN     NaN         NaN          NaN   iq  2013.0   7.0   6.0
397  NaN     NaN         NaN          NaN   iq  2013.0   8.0  12.0
398  NaN     NaN         NaN          NaN   iq  2013.0   9.0   5.0
399  NaN     NaN         NaN          NaN   iq  2013.0  10.0   6.0
400  NaN     NaN         NaN          NaN   iq  2013.0  11.0   9.0
401  NaN     NaN         NaN          NaN   iq  2013.0  12.0  12.0
402  NaN     NaN         NaN          NaN   iq  2013.0  13.0   9.0
403  NaN     NaN         NaN          NaN   iq  2013.0  14.0   6.0
404  NaN     NaN         NaN          NaN   iq  2013.0  15.0   6.0
405  NaN     NaN         NaN          NaN   iq  2013.0  16.0   9.0
406  NaN     NaN         NaN          NaN   iq  2013.0  17.0   5.0
407  NaN     NaN         NaN          NaN   iq  2013.0  18.0   7.0
408  NaN     NaN         NaN          NaN   iq  2013.0  19.0   4.0
409  NaN     NaN         NaN          NaN   iq  2013.0  20.0   4.0
410  NaN     NaN         NaN          NaN   iq  2013.0  21.0   3.0
411  NaN     NaN         NaN          NaN   iq  2013.0  22.0   3.0
412  NaN     NaN         NaN          NaN   iq  2013.0  23.0   5.0
413  NaN     NaN         NaN          NaN   iq  2013.0  24.0   1.0
414  NaN     NaN         NaN          NaN   iq  2013.0  25.0   4.0
415  NaN     NaN         NaN          NaN   iq  2013.0  26.0   3.0

[416 rows x 8 columns]

In [133]:
output = pd.concat([df_test.iloc[:,0:3],pd.DataFrame(y_holdout, columns=['total_cases'])], axis=1)
output.to_csv('submission.csv',index=False)

NameError: name 'y_holdout' is not defined